### Đăng ký
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "email":"vyhungle@gmail.com",
    "phoneNumber":"0983782940",
    "password":"vykt2000",
    "confirmPassword":"vykt2000",
    "fullName":"Lê Nguyễn Hùng Vỹ",
    "address":{
        "city":"TP.HCM",
        "district":"Tân phú",
        "ward":"Tây thạnh",
        "street":"37, T4A"
    },
    "dateOfBirth":"11/26/2000"
}

#### Đăng nhập
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "username":"0983782942",    
    "password":"vykt2000"
}

### get my user
GET http://localhost:4000/api/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzM2NGUxNTkwYWI1NDQ0MGUxMzQ1NCIsImVtYWlsIjoibG5odi4yNjExMjAwMEBnbWFpbC5jb20iLCJwaG9uZU51bWJlciI6IjA5ODM3ODI5NDIiLCJpYXQiOjE2MzA4MjIyMDUsImV4cCI6MTYzMjAzMTgwNX0.lQBc9CfSMvLSiuvmaDhqSoBpoIdGmdScm51H-FcDJWk