### Đăng ký
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "email":"lnhv.26112000@gmail.com",
    "phoneNumber":"0983782942",
    "password":"vykt2000",
    "confirmPassword":"vykt2000",
    "fullName":"Lê Nguyễn Hùng Vỹ",
    "address":{
        "city":"TP.HCM",
        "district":"Tân phú",
        "ward":"Tây thạnh",
        "street":"37, T4A"
    },
    "dateOfBirth":"11/26/2000"
}

#### Đăng nhập
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "username":"0983782942",    
    "password":"vykt2000"
}

### get my user
GET http://localhost:4000/api/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxM2RhMmQ4NzM2YWE4MjY4NDE0ODFiMyIsImVtYWlsIjoibG5odi4yNjExMjAwMEBnbWFpbC5jb20iLCJwaG9uZU51bWJlciI6IjA5ODM3ODI5NDIiLCJpYXQiOjE2MzE3MDk3NTYsImV4cCI6MTYzMjkxOTM1Nn0.r_ypgz-r67R6Vxq7-UrE7nYWuZNZ4DOZYYF7wlC5nvE


### send otp
POST http://localhost:4000/api/otp/send
Content-Type: application/json

{
    "phoneNumber":"0993783942"
}


###
POST http://localhost:4000/api/cast/add
Content-Type: application/json

{
     "name":"Craig Gillespie",
      "dateOfBirth":"9/1/1967",
      "image": "https://www.galaxycine.vn/media/c/r/craig-doc.png",
      "joinDate":"10/10/2015",
      "address":"Sydney, New South Wales, Australia",
      "phoneNumber":"0986521456",
      "email":"craig@gmail.com",
      "introduce":"",
      "male":true
}

###
GET http://localhost:4000/api/cast/all


###
GET http://localhost:4000/api/cast/614203ba5428a850a873bad2



###
POST http://localhost:4000/api/director/add
Content-Type: application/json

{
     "name":"Craig Gillespie",
      "dateOfBirth":"9/1/1967",
      "image": "https://www.galaxycine.vn/media/c/r/craig-doc.png",
      "joinDate":"10/10/2015",
      "address":"Sydney, New South Wales, Australia",
      "phoneNumber":"0986521456",
      "email":"craig@gmail.com",
      "introduce":"",
      "male":true
}

###
GET http://localhost:4000/api/director/all


###
GET http://localhost:4000/api/director/614207275f7f1a20b40891fe


###
POST http://localhost:4000/api/category/add
Content-Type: application/json

{
     "name":"Craig Gillespie",   
    "image": "https://www.galaxycine.vn/media/c/r/craig-doc.png"
     
}

###
GET http://localhost:4000/api/category/all


###
GET http://localhost:4000/api/category/6142088c6cb13f1f44d46cb9


